// Test generated by RoostGPT for test petstore using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.service;

import org.agoncal.application.petstore.model.Item;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import javax.persistence.EntityManager;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class CatalogService_findItem_8051e1116d_Test {

    @InjectMocks
    CatalogService catalogService;

    @Mock
    EntityManager em;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testFindItemSuccess() {
        Long itemId = 1L;
        Item mockItem = new Item();
        mockItem.setId(itemId);

        when(em.find(Item.class, itemId)).thenReturn(mockItem);

        Item item = catalogService.findItem(itemId);
        verify(em, times(1)).find(Item.class, itemId);

        assertEquals(mockItem, item);
    }

    @Test
    public void testFindItemFailure() {
        Long itemId = 2L;

        when(em.find(Item.class, itemId)).thenReturn(null);

        Item item = catalogService.findItem(itemId);
        verify(em, times(1)).find(Item.class, itemId);

        assertEquals(null, item);
    }
}
