// Test generated by RoostGPT for test petstore using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.service;

import org.agoncal.application.petstore.model.Item;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

import static org.mockito.Mockito.*;

public class CatalogService_removeItem_0714e553f9_Test {

    private CatalogService catalogService;
    private EntityManager em;
    private Item item;
    private TypedQuery<Item> typedQuery;

    @BeforeEach
    public void setup() {
        em = mock(EntityManager.class);
        catalogService = new CatalogService();
        catalogService.em = em;
        item = new Item();
        item.setId(1L);
        typedQuery = mock(TypedQuery.class);
    }

    @Test
    public void removeItem_test() {
        when(em.find(Item.class, item.getId())).thenReturn(item);
        doNothing().when(em).remove(item);

        catalogService.removeItem(item.getId());

        verify(em, times(1)).find(Item.class, item.getId());
        verify(em, times(1)).remove(item);
    }

    @Test
    public void removeItem_test_with_null() {
        when(em.find(Item.class, null)).thenReturn(null);
        doNothing().when(em).remove(null);

        catalogService.removeItem(null);

        verify(em, times(1)).find(Item.class, null);
        verify(em, times(1)).remove(null);
    }
}
