// Test generated by RoostGPT for test petstore using AI Type Open AI and AI Model gpt-4-1106-preview

package org.agoncal.application.petstore.service;

import org.agoncal.application.petstore.model.Product;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import javax.persistence.EntityManager;

import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class CatalogService_removeProduct_e04457ed1a_Test {

    @InjectMocks
    private CatalogService catalogService;

    @Mock
    private EntityManager em;

    private Product product;

    @BeforeEach
    public void setUp() {
        product = new Product();
        product.setId(1L);
        when(em.merge(product)).thenReturn(product);
    }

    @Test
    public void testRemoveProduct_Successful() {
        // Execute the method to be tested
        catalogService.removeProduct(product);

        // Verify that the entity manager is called with merge and remove
        verify(em).merge(product);
        verify(em).remove(product);
    }

    @Test
    public void testRemoveProduct_NullProduct() {
        // Execute the method with null product (should handle this case)
        catalogService.removeProduct(null);

        // Verify that the entity manager is never called when product is null
        verify(em, never()).merge(null);
        verify(em, never()).remove(null);
    }
}
