// Test generated by RoostGPT for test petstore using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.service;

import org.agoncal.application.petstore.model.Product;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import javax.persistence.EntityManager;

import static org.mockito.Mockito.*;

public class CatalogService_removeProduct_e04457ed1a_Test {

    @Mock
    EntityManager em;
    
    @InjectMocks
    CatalogService catalogService;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testRemoveProduct_Success() {
        Product product = new Product();
        product.setId(1L);
        product.setName("TestProduct");
        product.setDescription("TestDescription");

        catalogService.removeProduct(product);

        verify(em, times(1)).remove(product);
    }

    @Test
    public void testRemoveProduct_NullProduct() {
        Product product = null;
        
        catalogService.removeProduct(product);

        verify(em, times(0)).remove(any(Product.class));
    }
}
