// Test generated by RoostGPT for test petstore using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.service;

import org.agoncal.application.petstore.model.Product;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import javax.persistence.EntityManager;
import java.util.Optional;

import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.*;

public class CatalogService_removeProduct_0c8f39e4a1_Test {

    @InjectMocks
    CatalogService catalogService;

    @Mock
    EntityManager em;

    @Mock
    Product product;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    void removeProductTest_productExists() {
        when(em.find(Product.class, anyLong())).thenReturn(product);

        catalogService.removeProduct(1L);

        verify(em, times(1)).remove(any(Product.class));
    }

    @Test
    void removeProductTest_productDoesNotExist() {
        when(em.find(Product.class, anyLong())).thenReturn(null);

        catalogService.removeProduct(1L);

        verify(em, never()).remove(any(Product.class));
    }
}
