// Test generated by RoostGPT for test petstore using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.service;

import org.agoncal.application.petstore.model.Category;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import javax.persistence.EntityManager;
import javax.persistence.EntityNotFoundException;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class CatalogService_findCategory_e3c33f103a_Test {

    @Mock
    EntityManager em;

    @InjectMocks
    CatalogService catalogService;

    @Test
    public void testFindCategorySuccess() {
        Long categoryId = 1L;
        Category expectedCategory = new Category();
        expectedCategory.setId(categoryId);

        when(em.find(Category.class, categoryId)).thenReturn(expectedCategory);

        Category actualCategory = catalogService.findCategory(categoryId);

        assertEquals(expectedCategory, actualCategory);
        verify(em, times(1)).find(Category.class, categoryId);
    }

    @Test
    public void testFindCategoryFailure() {
        Long categoryId = 1L;

        when(em.find(Category.class, categoryId)).thenThrow(EntityNotFoundException.class);

        assertThrows(EntityNotFoundException.class, () -> catalogService.findCategory(categoryId));
        verify(em, times(1)).find(Category.class, categoryId);
    }
}
