// Test generated by RoostGPT for test petstore using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.service;

import org.agoncal.application.petstore.model.Category;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

import javax.persistence.EntityManager;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class CatalogService_removeCategory_d8859f27bd_Test {

    @InjectMocks
    private CatalogService catalogService;

    @Mock
    private EntityManager em;

    private Category category;

    @BeforeEach
    public void setup() {
        category = new Category();
        category.setId(1L);
        category.setName("TestCategory");
        category.setDescription("Test Category Description");
    }

    @Test
    public void testRemoveCategorySuccess() {
        when(em.merge(category)).thenReturn(category);

        catalogService.removeCategory(category);

        verify(em, times(1)).remove(category);
    }

    @Test
    public void testRemoveCategoryFailure() {
        when(em.merge(category)).thenThrow(new RuntimeException("Test Exception"));

        assertThrows(RuntimeException.class, () -> {
            catalogService.removeCategory(category);
        });

        verify(em, times(0)).remove(any());
    }

}
