// Test generated by RoostGPT for test petstore using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.service;

import org.agoncal.application.petstore.model.Category;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;

import javax.persistence.EntityManager;

public class CatalogService_createCategory_eedbe5c31d_Test {

    @InjectMocks
    CatalogService catalogService;

    @Mock
    EntityManager entityManager;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCreateCategorySuccess() {
        Category category = new Category();
        category.setId(1L);
        category.setName("Test Category");
        category.setDescription("This is a test category");

        Mockito.doNothing().when(entityManager).persist(Mockito.any(Category.class));

        Category result = catalogService.createCategory(category);

        Assertions.assertEquals(category, result);
        Mockito.verify(entityManager, Mockito.times(1)).persist(category);
    }

    @Test
    public void testCreateCategoryFailure() {
        Assertions.assertThrows(NullPointerException.class, () -> catalogService.createCategory(null));
    }
}
