// Test generated by RoostGPT for test petstore using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.service;

import org.agoncal.application.petstore.model.Item;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import javax.persistence.EntityManager;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class CatalogService_updateItem_8075f72dc3_Test {

    @InjectMocks
    CatalogService catalogService;

    @Mock
    EntityManager em;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testUpdateItemSuccess() {
        Item item = new Item();
        item.setId(1L);
        item.setName("TestItem");

        when(em.merge(any(Item.class))).thenReturn(item);

        Item updatedItem = catalogService.updateItem(item);

        verify(em, times(1)).merge(item);
        assertEquals(item, updatedItem);
    }

    @Test
    public void testUpdateItemFailure() {
        Item item = new Item();
        item.setId(1L);
        item.setName("TestItem");

        when(em.merge(any(Item.class))).thenReturn(null);

        Item updatedItem = catalogService.updateItem(item);

        verify(em, times(1)).merge(item);
        assertEquals(null, updatedItem);
    }
}
