// Test generated by RoostGPT for test petstore using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.service;

import org.agoncal.application.petstore.model.Item;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import javax.persistence.EntityManager;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

public class CatalogService_removeItem_e6b5aec609_Test {

    @InjectMocks
    CatalogService catalogService;

    @Mock
    EntityManager em;

    @Mock
    Item item;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testRemoveItem() {
        doNothing().when(em).remove(any());
        catalogService.removeItem(item);

        verify(em, times(1)).merge(item);
        verify(em, times(1)).remove(any());
    }

    @Test
    public void testRemoveNullItem() {
        doNothing().when(em).remove(any());
        catalogService.removeItem(null);

        verify(em, times(0)).merge(any());
        verify(em, times(0)).remove(any());
    }
}
