// Test generated by RoostGPT for test petstore using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.service;

import org.agoncal.application.petstore.model.Category;
import org.agoncal.application.petstore.model.Product;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;

import javax.persistence.EntityManager;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class CatalogService_createProduct_ea5de5b610_Test {

    @Mock
    private EntityManager em;

    @InjectMocks
    private CatalogService catalogService;

    @Test
    public void testCreateProductWithCategory() {
        Product product = new Product();
        Category category = new Category();
        product.setCategory(category);

        catalogService.createProduct(product);

        verify(em, times(1)).persist(category);
        verify(em, times(1)).persist(product);
    }

    @Test
    public void testCreateProductWithoutCategory() {
        Product product = new Product();

        catalogService.createProduct(product);

        verify(em, times(0)).persist(any(Category.class));
        verify(em, times(1)).persist(product);
    }
}
