// Test generated by RoostGPT for test petstore using AI Type Open AI and AI Model gpt-4

package org.agoncal.application.petstore.service;

import org.agoncal.application.petstore.model.Category;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import javax.persistence.EntityManager;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class CatalogService_updateCategory_f8f422915e_Test {

    @InjectMocks
    CatalogService catalogService;

    @Mock
    EntityManager em;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testUpdateCategory_Success() {
        Category category = new Category();
        category.setId(1L);
        category.setName("Test Category");

        when(em.merge(category)).thenReturn(category);

        Category result = catalogService.updateCategory(category);

        assertEquals(category, result);
        verify(em, times(1)).merge(category);
    }

    @Test
    public void testUpdateCategory_Failure() {
        Category category = new Category();
        category.setId(1L);
        category.setName("Test Category");

        when(em.merge(category)).thenReturn(null);

        Category result = catalogService.updateCategory(category);

        assertEquals(null, result);
        verify(em, times(1)).merge(category);
    }
}
